openapi: "3.0.0"
info:
    version: "1.0.0"
    title: "Dinosaurs API"
    description: Handle Dinosaurs

paths:
    /dinosaurs/{dinosaurId}:
        parameters:
            - name: dinosaurId
              description: The unique identifier of the Dinosaurs
              in: path
              required: true
              schema:
                  $ref: "#/components/schemas/DinosaurId"
        get:
            summary: Read a dinosaur
            responses:
                "200":
                    description: The dinosaur corresponding to the provided `dinosaurId`
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Dinosaur"
                404:
                    description: No dinosaur found for the provided `dinosaurId`
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"
                500:
                    description: Unexpected error
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"
components:
    schemas:
        DinosaurId:
            description: The unique identifier of a dinosaur
            type: string
        Dinosaur:
            $ref: './schemas/Dinosaur.yaml'
        Error:
            type: object
            required:
                - message
            properties:
                message:
                    description: A human readable error message
                    type: string
    securitySchemes:
        ApiKey:
            type: apiKey
            in: header
            name: X-Api-Key
security:
    - ApiKey: []
