openapi: "3.0.1"
servers:
    - url: https://396cee42-4c57-45c6-abdc-ea31105be27f.mock.pstmn.io
      description: Mock server
info:
    version: "1.0.0"
    title: "Dinosaurs API"
    description: Handle Dinosaurs

paths:
    /v1/dinosaurs:
        get:
            summary: Get all dinosaurs
            responses:
                200:
                    description: All existing and alive dinosaurs
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Dinosaurs"
                401:
                    $ref: "#/components/responses/UnauthorizedError"
                403:
                    $ref: "#/components/responses/ForbiddenError"
                500:
                    $ref: "#/components/responses/UnexpectedError"
            security: 
                - OAuth2: 
                    - read:dinosaurs
            
    /v1/dinosaurs/{dinosaurId}:
        parameters:
            - $ref: "#/components/parameters/dinosaurId"
        get:
            summary: Get a specific dinosaur by its id
            responses:
                200:
                    description: The dinosaur corresponding to the provided `dinosaurId`
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Dinosaur"
                204:
                    $ref: "#/components/responses/NotFoundError"
                401:
                    $ref: "#/components/responses/UnauthorizedError"
                403:
                    $ref: "#/components/responses/ForbiddenError"
                500:
                    $ref: "#/components/responses/UnexpectedError"
            security: 
                - OAuth2: 
                    - read:dinosaurs

components:
    schemas:
        DinosaurId:
            $ref: "./schemas/DinosaurId.yaml"
        Dinosaur:
            $ref: "./schemas/Dinosaur.yaml"
        Dinosaurs:
            $ref: "./schemas/Dinosaurs.yaml"
        Error:
            $ref: "./schemas/Error.yaml"
    parameters:
        dinosaurId:
            $ref: "./parameters/path/DinosaurId.yaml"
    responses:
        ForbiddenError:
            description: The access to the requested resource is prohibited
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/Error"
        NotFoundError:
            description: No dinosaur found for the provided `dinosaurId`
        UnauthorizedError:
            description: Access token is missing or invalid
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/Error"
        UnexpectedError:
            description: Unexpected error
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/Error"
    securitySchemes:
        OAuth2:
            type: oauth2
            description: tokenUrl --> https://breizhcamp.eu.auth0.com/oauth/token
            flows: 
                clientCredentials: 
                    tokenUrl: https://breizhcamp.eu.auth0.com/oauth/token
                    scopes:
                        read:dinosaurs: Grants read dinosaurs access
                        update:dinosaurs: Grants write access
                        delete:dinosaurs: Grants access to admin operations
