name: Automated API tests - Postman CLI

on: push

env:
  DINOSAURS_API_ID: ed430ec7-957d-44d6-b154-46d7de092773
  COLLECTION_ID: 24574593-b537b40b-930a-4255-85b8-fe85e71026d8
  ENVIRONMENT_ID: 24574593-5c19695f-a80c-4e99-8efe-20b61147ce3f
  POSTMAN_INTEGRATION_ID: 141759
  GITHUB_INTEGRATION_ID: 141759-${{ github.run_id }}
  POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}

jobs:
  postman-cli-collection-path:
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out repository under $GITHUB_WORKSPACE
        uses: actions/checkout@v3
      - name: Install Postman CLI
        run: curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ env.POSTMAN_API_KEY }}
      - name: Run API tests with Postman CLI
        run: postman collection run ${{ github.workspace }}/postman/collections/Dinosaurs_API.json --environment ${{ env.ENVIRONMENT_ID }} --integration-id ${{ env.GITHUB_INTEGRATION_ID }}
      - name: Lint API with Postman CLI
        run: postman api lint ${{ env.DINOSAURS_API_ID }} --integration-id ${{ env.POSTMAN_INTEGRATION_ID }}

  postman-cli-collection-id:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ env.POSTMAN_API_KEY }}
      - name: Run API tests with Postman CLI
        run: postman collection run ${{ env.COLLECTION_ID }} --environment ${{ env.ENVIRONMENT_ID }} --integration-id ${{ env.GITHUB_INTEGRATION_ID }}
