name: Automated API tests - Newman

on: push

env:
  COLLECTION_ID: 28191179-c7fa9d9d-fab7-4224-b162-90203eba11f2
  ENVIRONMENT_ID: 28191179-f9236695-9a41-4a9b-8126-cbabf1fcbd20
  POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}

jobs:
  newman-collection-path:
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out repository under $GITHUB_WORKSPACE
        uses: actions/checkout@master
      - name: Install Newman
        run: npm install -g newman
      - name: Run collection with Newman
        run: newman run ${{ github.workspace }}/do-not-concern-the-api-def/collections/05_Tests_fonctionnels.json --environment https://api.postman.com/environments/${{ env.ENVIRONMENT_ID }}?apikey=${{ env.POSTMAN_API_KEY }}

  newman-collection-id:
    runs-on: ubuntu-latest
    needs: newman-collection-path # to avoid conflict in the functional tests
    steps:
      - name: Checks-out your repository under $GITHUB_WORKSPACE
        uses: actions/checkout@master
      - name: Install Newman
        run: npm install -g newman
      - name: Run collection with Newman
        run: newman run https://api.postman.com/collections/${{ env.COLLECTION_ID }}?apikey=${{ env.POSTMAN_API_KEY }} --environment https://api.postman.com/environments/${{ env.ENVIRONMENT_ID }}?apikey=${{ env.POSTMAN_API_KEY }}