name: Automated API tests - Postman CLI

# Only trigger, when the "Automated API tests" - Newman workflow succeeded
on:
  workflow_run:
    workflows: ["Automated API tests - Newman"]
    types:
      - completed
env:
  COLLECTION_ID: 28191179-c7fa9d9d-fab7-4224-b162-90203eba11f2
  ENVIRONMENT_ID: 28191179-f9236695-9a41-4a9b-8126-cbabf1fcbd20
  POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}

jobs:
  postman-cli-collection-path:
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out repository under $GITHUB_WORKSPACE
        uses: actions/checkout@v3
      - name: Install Postman CLI
        run: curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ env.POSTMAN_API_KEY }}
      - name: Run API tests with Postman CLI
        run: postman collection run ${{ github.workspace }}/do-not-concern-the-api-def/collections/05_Tests_fonctionnels.json --environment ${{ env.ENVIRONMENT_ID }}

  postman-cli-collection-id:
    runs-on: ubuntu-latest
    needs: postman-cli-collection-path # to avoid conflict in the functional tests
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ env.POSTMAN_API_KEY }}
      - name: Run API tests with Postman CLI
        run: postman collection run ${{ env.COLLECTION_ID }} --environment ${{ env.ENVIRONMENT_ID }}
