name: Automated API tests using Newman

on: push

jobs:
  newman-collection-path:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:
          apiKey: ${{ secrets.POSTMAN_API_KEY }}
          collection: ${{ github.workspace }}/postman/collections/Dinosaurs API.json
          environment: 24574593-9f1b3d85-9080-47b5-bd81-95ed440581c1
  newman-collection-id:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:
          apiKey: ${{ secrets.POSTMAN_API_KEY }}
          collection: 24574593-983858f8-752e-43a6-a3bd-6b6abe7dad6a
          environment: 24574593-9f1b3d85-9080-47b5-bd81-95ed440581c1